-- Database: BasicCMS

-- Hora de crear tablas

CREATE TABLE Roles(
	Id int primary key generated by default as identity,
	Nombre varchar(30) not null,
	Descripcion varchar(150)
);

CREATE TABLE Usuarios(
	Id int primary key generated by default as identity,
	Nombre varchar(30) not null,
	ApellidoP varchar(30) not null,
	ApellidoM varchar(30) not null,
	NombreUsuario varchar(50) not null,
	PasswordHash varchar(900) not null,
	PasswordSalt varchar(500) not null
);

CREATE TABLE Usuarios_Roles(
	UsuarioId int,
	RoleId int,
	primary key (UsuarioId, RoleId),
	foreign key (UsuarioId) references Usuarios(Id),
	foreign key (RoleId) references Roles(Id)
);

CREATE TABLE Articulos
(
	Id int primary key generated by default as identity,
	Titulo varchar(50) not null,
	Contenido text not null,
	Fecha_Pub timestamp with time zone not null,
	AutorId int,
	constraint FK_ArticuloAutor foreign key (AutorId) references Usuarios(Id)
);

CREATE TABLE Categorias(
	Id int primary key generated by default as identity,
	Nombre varchar(30) not null,
	Descripcion varchar(150)
);

CREATE TABLE Articulos_Categorias(
	ArticuloId int,
	CategoriaId int,
	primary key (ArticuloId, CategoriaId),
	constraint FK_AC_Articulo foreign key (ArticuloId) references Articulos(Id)
		match simple
		on update no action
		on delete cascade,
	constraint FK_AC_Categoria foreign key (CategoriaId) references Categorias(Id)
		match simple
		on update no action
		on delete cascade
);

CREATE TABLE Comentarios(
	Id int primary key generated by default as identity,
	Texto text,
	Fecha_Pub timestamp with time zone,
	AutorId int,
	ArticuloId int not null,
	constraint FK_ComentarioUsuario foreign key (AutorId) references Usuarios(Id)
		match simple
		on update no action
		on delete cascade,
	constraint FK_ComentarioArticulo foreign key (ArticuloId) references Articulos(Id)
		match simple
		on update no action
		on delete cascade
);